# Generated by Django 3.0.5 on 2021-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_currency', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_simbol', models.BooleanField(default=False)),
                ('currency_before', models.BooleanField(default=False)),
                ('show_cents', models.BooleanField(default=False)),
                ('dot_delimiter', models.BooleanField(default=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_currency', models.CharField(max_length=50)),
            ],
        ),
    ]
