# Generated by Django 3.0.5 on 2021-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_formats', '0002_auto_20210326_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
