# Generated by Django 3.0.5 on 2021-03-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_formats', '0003_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='valueText',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
